import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'de' | 'es' | 'fr' | 'it' | 'nl' | 'pt' | 'tr' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const languages = {
  en: { name: 'English', flag: '🇺🇸' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  es: { name: 'Español', flag: '🇪🇸' },
  fr: { name: 'Français', flag: '🇫🇷' },
  it: { name: 'Italiano', flag: '🇮🇹' },
  nl: { name: 'Nederlands', flag: '🇳🇱' },
  pt: { name: 'Português', flag: '🇵🇹' },
  tr: { name: 'Turkish', flag: '🇹🇷' },
  zh: { name: 'Chinese', flag: '🇨🇳' },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') as Language;
    if (savedLanguage && languages[savedLanguage]) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    const translations = getTranslations(language);
    return translations[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

function getTranslations(lang: Language) {
  const translations: Record<Language, Record<string, string>> = {
    en: {
      // Header
      'ambassador.platform': 'Ambassador platform',
      'connect.wallet': 'Connect Wallet',
      'connected': 'Connected',
      'connecting': 'Connecting...',
      'connect': 'Connect',
      
      // Navigation
      'dashboard': 'Dashboard',
      'submit.contribution': 'Submit Contribution',
      'leaderboard': 'Leaderboard',
      'your.analytics': 'Your Analytics',
      'settings': 'Settings',
      'help': 'Help',
      
      // Common
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'cancel': 'Cancel',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'view': 'View',
      'close': 'Close',
      'submit': 'Submit',
      'back': 'Back',
      'next': 'Next',
      'previous': 'Previous',
      
      // Dashboard
      'welcome.back': 'Welcome back',
      'total.contributions': 'Total Contributions',
      'total.points': 'Total Points',
      'rank': 'Rank',
      'recent.activity': 'Recent Activity',
      'no.activity': 'No recent activity',
      
      // Contribution Form
      'contribution.title': 'Submit Your Contribution',
      'contribution.description': 'Share your work and earn points',
      'contribution.type': 'Contribution Type',
      'contribution.title.label': 'Title',
      'contribution.title.placeholder': 'Enter contribution title',
      'contribution.description.label': 'Description',
      'contribution.description.placeholder': 'Describe your contribution',
      'contribution.url.label': 'URL (Optional)',
      'contribution.url.placeholder': 'https://example.com',
      'contribution.category': 'Category',
      'contribution.category.content': 'Content Creation',
      'contribution.category.development': 'Development',
      'contribution.category.community': 'Community',
      'contribution.category.translation': 'Translation',
      'contribution.category.other': 'Other',
      
      // Leaderboard
      'leaderboard.title': 'Leaderboard',
      'leaderboard.description': 'Top contributors this month',
      'rank.position': 'Rank',
      'user': 'User',
      'points': 'Points',
      'contributions': 'Contributions',
      
      // Analytics
      'analytics.title': 'Your Analytics',
      'analytics.description': 'Track your performance and growth',
      'analytics.overview': 'Overview',
      'analytics.contributions.chart': 'Contributions Over Time',
      'analytics.points.chart': 'Points Earned',
      'analytics.activity.chart': 'Activity Heatmap',
      
      // Blog
      'blog.title': 'Latest Updates',
      'blog.description': 'Stay informed with the latest developments from the Qubic team.',
      'blog.read.more': 'Read More',
      'blog.published': 'Published',
      
      // Footer
      'footer.copyright': '© 2025 Qubic Platform. All rights reserved.',
      'footer.privacy': 'Privacy Policy',
      'footer.terms': 'Terms of Service',
      'footer.version': 'Version 1.0.2',
      
      // Language
      'language': 'Language',
      'select.language': 'Select Language',
      
      // Visitor Page
      'visitor.active.ambassadors': 'Active Ambassadors',
      'visitor.total.contributions': 'Total Contributions',
      'visitor.growth.this.week': 'Growth This Week',
      'visitor.this.week': 'This Week',
      'visitor.all.time': 'All Time',
      'visitor.last.activity': 'Last Activity',
      'visitor.about.program': 'About the Ambassador Program',
      'visitor.about.description': 'The Qubic Ambassador Program recognizes and rewards community members who actively contribute to the growth and success of the Qubic ecosystem.',
      'visitor.join.community': 'Join the Community',
      'visitor.join.description': 'Interested in becoming a Qubic Ambassador? Connect your wallet to explore opportunities and start contributing to the ecosystem.',
      'visitor.why.join': 'Why join the program?',
      'visitor.why.join.description': 'Become part of the Qubic community and earn rewards for your contributions',
      'visitor.community.building': 'Community Building',
      'visitor.community.building.description': 'Connect with fellow ambassadors and grow the Qubic community through engaging content and events.',
      'visitor.track.performance': 'Track Performance',
      'visitor.track.performance.description': 'Monitor your impact with real-time analytics and see how your contributions drive engagement.',
      'visitor.earn.rewards': 'Earn Rewards',
      'visitor.earn.rewards.description': 'Complete tasks and climb the leaderboard to earn points and recognition in the community.',
      'visitor.connect.wallet.step': 'Connect your Qubic wallet',
      'visitor.verification.step': 'Complete verification process',
      'visitor.start.earning.step': 'Start earning points for contributions',
      'visitor.twitter.badge': '🐦 Twitter',
      'visitor.github.badge': '💻 GitHub',
      'visitor.content.badge': '📝 Content',
      'visitor.social.media.engagement': 'Social media engagement',
      'visitor.technical.contributions': 'Technical contributions',
      'visitor.educational.content': 'Educational content creation',
      
      // Leaderboard additional texts
      'leaderboard.this.week': 'This Week',
      'leaderboard.all.time': 'All Time',
      'leaderboard.last.activity': 'Last Activity',
      'leaderboard.top.contributor': 'Top Contributor',
      'leaderboard.active.contributor': 'Active Contributor',
      'leaderboard.rising.star': 'Rising Star',
      'leaderboard.ambassador': 'Ambassador',
      'leaderboard.just.now': 'Just now',
      'leaderboard.hours.ago': 'hours ago',
      'leaderboard.days.ago': 'days ago',
      
      // Recent Activity
      'recent.activity.title': 'Recent Activity',
      'recent.activity.no.activity': 'No recent activity found.',
      'recent.activity.start.contributing': 'Start contributing to see your activity here!',
      'recent.activity.points': 'point',
      'recent.activity.points.plural': 'points',
      
      // Dashboard Stats
      'from.last.week': 'from last week',
      'this.week': 'this week',
      'up.positions': 'Up',
      'positions': 'positions',
      'points.this.week': 'points this week',
      
      // Charts
      'your.contribution.trend': 'Your Contribution Trend',
      'contribution.types': 'Contribution Types',
      'your.points': 'Your Points',
      'community.average': 'Community Average',
      
      // ContributionForm
      'url': 'URL',
      'url.paste.description': 'Paste the URL of your contribution (Twitter post, GitHub commit, etc.)',
      'description.optional': 'Description (Optional)',
      'brief.description': 'Brief description of your contribution...',
      'validation.rules': 'Validation Rules',
      'validation.rule.1': 'URLs must be public and accessible',
      'validation.rule.2': 'Twitter posts must mention @QubicOfficial or #Qubic',
      'validation.rule.3': 'GitHub commits must be in Qubic-related repositories',
      'validation.rule.4': 'Duplicate submissions will be rejected',
      'validation.rule.5': 'Each contribution type has a cooldown period',
      
      // Analytics
      'your.performance': 'Your Performance',
      'weekly.average': 'Weekly Average',
      'best.week': 'Best Week',
      'consistency.score': 'Consistency Score',
      'total.streak': 'Total Streak',
      'monthly.goal': 'Monthly Goal',
      'target': 'Target',
      'points.to.go': 'points to go',
      'days.remaining': 'days remaining',
      'detailed.analytics': 'Detailed Analytics',
      'points.unit': 'points',
      'days.unit': 'days',
    },
    de: {
      'ambassador.platform': 'Botschafter-Plattform',
      'connect.wallet': 'Wallet verbinden',
      'connected': 'Verbunden',
      'connecting': 'Verbinde...',
      'connect': 'Verbinden',
      'dashboard': 'Dashboard',
      'submit.contribution': 'Beitrag einreichen',
      'leaderboard': 'Rangliste',
      'your.analytics': 'Ihre Analysen',
      'settings': 'Einstellungen',
      'help': 'Hilfe',
      'loading': 'Laden...',
      'error': 'Fehler',
      'success': 'Erfolg',
      'cancel': 'Abbrechen',
      'save': 'Speichern',
      'delete': 'Löschen',
      'edit': 'Bearbeiten',
      'view': 'Anzeigen',
      'close': 'Schließen',
      'submit': 'Einreichen',
      'back': 'Zurück',
      'next': 'Weiter',
      'previous': 'Vorherige',
      'welcome.back': 'Willkommen zurück',
      'total.contributions': 'Gesamtbeiträge',
      'total.points': 'Gesamtpunkte',
      'rank': 'Rang',
      'recent.activity': 'Letzte Aktivität',
      'no.activity': 'Keine kürzliche Aktivität',
      'contribution.title': 'Beitrag einreichen',
      'contribution.description': 'Teilen Sie Ihre Arbeit und verdienen Sie Punkte',
      'contribution.type': 'Beitragstyp',
      'contribution.title.label': 'Titel',
      'contribution.title.placeholder': 'Beitragstitel eingeben',
      'contribution.description.label': 'Beschreibung',
      'contribution.description.placeholder': 'Beschreiben Sie Ihren Beitrag',
      'contribution.url.label': 'URL (Optional)',
      'contribution.url.placeholder': 'https://example.com',
      'contribution.category': 'Kategorie',
      'contribution.category.content': 'Content Creation',
      'contribution.category.development': 'Entwicklung',
      'contribution.category.community': 'Community',
      'contribution.category.translation': 'Übersetzung',
      'contribution.category.other': 'Andere',
      'leaderboard.title': 'Rangliste',
      'leaderboard.description': 'Top-Beitragende diesen Monat',
      'rank.position': 'Rang',
      'user': 'Benutzer',
      'points': 'Punkte',
      'contributions': 'Beiträge',
      'analytics.title': 'Ihre Analysen',
      'analytics.description': 'Verfolgen Sie Ihre Leistung und Ihr Wachstum',
      'analytics.overview': 'Übersicht',
      'analytics.contributions.chart': 'Beiträge im Zeitverlauf',
      'analytics.points.chart': 'Verdiente Punkte',
      'analytics.activity.chart': 'Aktivitäts-Heatmap',
      'blog.title': 'Neueste Updates',
      'blog.description': 'Bleiben Sie über die neuesten Entwicklungen vom Qubic-Team informiert.',
      'blog.read.more': 'Weiterlesen',
      'blog.published': 'Veröffentlicht',
      'footer.copyright': '© 2025 Qubic Platform. Alle Rechte vorbehalten.',
      'footer.privacy': 'Datenschutzrichtlinie',
      'footer.terms': 'Nutzungsbedingungen',
      'footer.version': 'Version 1.0.2',
      'language': 'Sprache',
      'select.language': 'Sprache auswählen',
      'visitor.active.ambassadors': 'Aktive Botschafter',
      'visitor.total.contributions': 'Gesamtbeiträge',
      'visitor.growth.this.week': 'Wachstum diese Woche',
      'visitor.this.week': 'Diese Woche',
      'visitor.all.time': 'Gesamtzeit',
      'visitor.last.activity': 'Letzte Aktivität',
      'visitor.about.program': 'Über das Botschafter-Programm',
      'visitor.about.description': 'Das Qubic Botschafter-Programm erkennt Community-Mitglieder an und belohnt sie, die aktiv zum Wachstum und Erfolg des Qubic-Ökosystems beitragen.',
      'visitor.join.community': 'Community beitreten',
      'visitor.join.description': 'Interessiert daran, Qubic-Botschafter zu werden? Verbinden Sie Ihre Wallet, um Möglichkeiten zu erkunden und zum Ökosystem beizutragen.',
      'visitor.why.join': 'Warum dem Programm beitreten?',
      'visitor.why.join.description': 'Werden Sie Teil der Qubic-Community und verdienen Sie Belohnungen für Ihre Beiträge',
      'visitor.community.building': 'Community-Aufbau',
      'visitor.community.building.description': 'Verbinden Sie sich mit anderen Botschaftern und wachsen Sie die Qubic-Community durch ansprechende Inhalte und Events.',
      'visitor.track.performance': 'Leistung verfolgen',
      'visitor.track.performance.description': 'Überwachen Sie Ihre Auswirkungen mit Echtzeit-Analysen und sehen Sie, wie Ihre Beiträge Engagement fördern.',
      'visitor.earn.rewards': 'Belohnungen verdienen',
      'visitor.earn.rewards.description': 'Vervollständigen Sie Aufgaben und steigen Sie in der Rangliste auf, um Punkte und Anerkennung in der Community zu verdienen.',
      'visitor.connect.wallet.step': 'Verbinden Sie Ihre Qubic-Wallet',
      'visitor.verification.step': 'Verifizierungsprozess abschließen',
      'visitor.start.earning.step': 'Beginnen Sie mit dem Verdienen von Punkten für Beiträge',
      'visitor.twitter.badge': '🐦 Twitter',
      'visitor.github.badge': '💻 GitHub',
      'visitor.content.badge': '📝 Inhalt',
      'visitor.social.media.engagement': 'Social Media Engagement',
      'visitor.technical.contributions': 'Technische Beiträge',
      'visitor.educational.content': 'Bildungsinhalte erstellen',
      'leaderboard.this.week': 'Diese Woche',
      'leaderboard.all.time': 'Gesamtzeit',
      'leaderboard.last.activity': 'Letzte Aktivität',
      'leaderboard.top.contributor': 'Top-Beitragender',
      'leaderboard.active.contributor': 'Aktiver Beitragender',
      'leaderboard.rising.star': 'Aufsteigender Stern',
      'leaderboard.ambassador': 'Botschafter',
      'leaderboard.just.now': 'Gerade eben',
      'leaderboard.hours.ago': 'Stunden her',
      'leaderboard.days.ago': 'Tage her',
      'recent.activity.title': 'Letzte Aktivität',
      'recent.activity.no.activity': 'Keine kürzliche Aktivität gefunden.',
      'recent.activity.start.contributing': 'Beginnen Sie mit Beiträgen, um Ihre Aktivität hier zu sehen!',
      'recent.activity.points': 'Punkt',
      'recent.activity.points.plural': 'Punkte',
      
      // Dashboard Stats
      'from.last.week': 'von letzter Woche',
      'this.week': 'diese Woche',
      'up.positions': 'Auf',
      'positions': 'Positionen',
      'points.this.week': 'Punkte diese Woche',
      
      // Charts
      'your.contribution.trend': 'Ihr Beitragstrend',
      'contribution.types': 'Beitragstypen',
      'your.points': 'Ihre Punkte',
      'community.average': 'Community-Durchschnitt',
      
      // ContributionForm
      'url': 'URL',
      'url.paste.description': 'Fügen Sie die URL Ihres Beitrags ein (Twitter-Post, GitHub-Commit, etc.)',
      'description.optional': 'Beschreibung (Optional)',
      'brief.description': 'Kurze Beschreibung Ihres Beitrags...',
      'validation.rules': 'Validierungsregeln',
      'validation.rule.1': 'URLs müssen öffentlich und zugänglich sein',
      'validation.rule.2': 'Twitter-Posts müssen @QubicOfficial oder #Qubic erwähnen',
      'validation.rule.3': 'GitHub-Commits müssen in Qubic-bezogenen Repositories sein',
      'validation.rule.4': 'Doppelte Einreichungen werden abgelehnt',
      'validation.rule.5': 'Jeder Beitragstyp hat eine Abkühlzeit',
      
      // Analytics
      'your.performance': 'Ihre Leistung',
      'weekly.average': 'Wöchentlicher Durchschnitt',
      'best.week': 'Beste Woche',
      'consistency.score': 'Konsistenz-Score',
      'total.streak': 'Gesamtsträhne',
      'monthly.goal': 'Monatsziel',
      'target': 'Ziel',
      'points.to.go': 'Punkte zu gehen',
      'days.remaining': 'Tage verbleibend',
      'detailed.analytics': 'Detaillierte Analysen',
      'points.unit': 'Punkte',
      'days.unit': 'Tage',
    },
    es: {
      'ambassador.platform': 'Plataforma de Embajadores',
      'connect.wallet': 'Conectar Billetera',
      'connected': 'Conectado',
      'connecting': 'Conectando...',
      'connect': 'Conectar',
      'dashboard': 'Panel de Control',
      'submit.contribution': 'Enviar Contribución',
      'leaderboard': 'Clasificación',
      'your.analytics': 'Tus Análisis',
      'settings': 'Configuración',
      'help': 'Ayuda',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'cancel': 'Cancelar',
      'save': 'Guardar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'view': 'Ver',
      'close': 'Cerrar',
      'submit': 'Enviar',
      'back': 'Atrás',
      'next': 'Siguiente',
      'previous': 'Anterior',
      'welcome.back': 'Bienvenido de vuelta',
      'total.contributions': 'Contribuciones Totales',
      'total.points': 'Puntos Totales',
      'rank': 'Rango',
      'recent.activity': 'Actividad Reciente',
      'no.activity': 'Sin actividad reciente',
      'contribution.title': 'Enviar Tu Contribución',
      'contribution.description': 'Comparte tu trabajo y gana puntos',
      'contribution.type': 'Tipo de Contribución',
      'contribution.title.label': 'Título',
      'contribution.title.placeholder': 'Ingresa el título de la contribución',
      'contribution.description.label': 'Descripción',
      'contribution.description.placeholder': 'Describe tu contribución',
      'contribution.url.label': 'URL (Opcional)',
      'contribution.url.placeholder': 'https://example.com',
      'contribution.category': 'Categoría',
      'contribution.category.content': 'Creación de Contenido',
      'contribution.category.development': 'Desarrollo',
      'contribution.category.community': 'Comunidad',
      'contribution.category.translation': 'Traducción',
      'contribution.category.other': 'Otro',
      'leaderboard.title': 'Clasificación',
      'leaderboard.description': 'Mejores contribuyentes este mes',
      'rank.position': 'Rango',
      'user': 'Usuario',
      'points': 'Puntos',
      'contributions': 'Contribuciones',
      'analytics.title': 'Tus Análisis',
      'analytics.description': 'Rastrea tu rendimiento y crecimiento',
      'analytics.overview': 'Resumen',
      'analytics.contributions.chart': 'Contribuciones en el Tiempo',
      'analytics.points.chart': 'Puntos Ganados',
      'analytics.activity.chart': 'Mapa de Calor de Actividad',
      'blog.title': 'Últimas Actualizaciones',
      'blog.description': 'Mantente informado sobre los últimos desarrollos del equipo Qubic.',
      'blog.read.more': 'Leer Más',
      'blog.published': 'Publicado',
      'footer.copyright': '© 2025 Qubic Platform. Todos los derechos reservados.',
      'footer.privacy': 'Política de Privacidad',
      'footer.terms': 'Términos de Servicio',
      'footer.version': 'Versión 1.0.2',
      'language': 'Idioma',
      'select.language': 'Seleccionar Idioma',
      'visitor.active.ambassadors': 'Embajadores Activos',
      'visitor.total.contributions': 'Contribuciones Totales',
      'visitor.growth.this.week': 'Crecimiento Esta Semana',
      'visitor.this.week': 'Esta Semana',
      'visitor.all.time': 'Todo el Tiempo',
      'visitor.last.activity': 'Última Actividad',
      'visitor.about.program': 'Acerca del Programa de Embajadores',
      'visitor.about.description': 'El Programa de Embajadores de Qubic reconoce y recompensa a los miembros de la comunidad que contribuyen activamente al crecimiento y éxito del ecosistema Qubic.',
      'visitor.join.community': 'Únete a la Comunidad',
      'visitor.join.description': '¿Interesado en convertirte en Embajador de Qubic? Conecta tu billetera para explorar oportunidades y comenzar a contribuir al ecosistema.',
      'visitor.why.join': '¿Por qué unirse al programa?',
      'visitor.why.join.description': 'Conviértete en parte de la comunidad Qubic y gana recompensas por tus contribuciones',
      'visitor.community.building': 'Construcción de Comunidad',
      'visitor.community.building.description': 'Conéctate con otros embajadores y haz crecer la comunidad Qubic a través de contenido atractivo y eventos.',
      'visitor.track.performance': 'Seguimiento de Rendimiento',
      'visitor.track.performance.description': 'Monitorea tu impacto con análisis en tiempo real y ve cómo tus contribuciones impulsan el compromiso.',
      'visitor.earn.rewards': 'Ganar Recompensas',
      'visitor.earn.rewards.description': 'Completa tareas y sube en la tabla de clasificación para ganar puntos y reconocimiento en la comunidad.',
      'visitor.connect.wallet.step': 'Conecta tu billetera Qubic',
      'visitor.verification.step': 'Completa el proceso de verificación',
      'visitor.start.earning.step': 'Comienza a ganar puntos por contribuciones',
      'visitor.twitter.badge': '🐦 Twitter',
      'visitor.github.badge': '💻 GitHub',
      'visitor.content.badge': '📝 Contenido',
      'visitor.social.media.engagement': 'Compromiso en redes sociales',
      'visitor.technical.contributions': 'Contribuciones técnicas',
      'visitor.educational.content': 'Creación de contenido educativo',
      'leaderboard.this.week': 'Esta Semana',
      'leaderboard.all.time': 'Todo el Tiempo',
      'leaderboard.last.activity': 'Última Actividad',
      'leaderboard.top.contributor': 'Mejor Contribuyente',
      'leaderboard.active.contributor': 'Contribuyente Activo',
      'leaderboard.rising.star': 'Estrella Emergente',
      'leaderboard.ambassador': 'Embajador',
      'leaderboard.just.now': 'Ahora mismo',
      'leaderboard.hours.ago': 'horas atrás',
      'leaderboard.days.ago': 'días atrás',
      'recent.activity.title': 'Actividad Reciente',
      'recent.activity.no.activity': 'No se encontró actividad reciente.',
      'recent.activity.start.contributing': '¡Comienza a contribuir para ver tu actividad aquí!',
      'recent.activity.points': 'punto',
      'recent.activity.points.plural': 'puntos',
      
      // Dashboard Stats
      'from.last.week': 'desde la semana pasada',
      'this.week': 'esta semana',
      'up.positions': 'Subió',
      'positions': 'posiciones',
      'points.this.week': 'puntos esta semana',
      
      // Charts
      'your.contribution.trend': 'Tu Tendencia de Contribuciones',
      'contribution.types': 'Tipos de Contribución',
      'your.points': 'Tus Puntos',
      'community.average': 'Promedio de la Comunidad',
      
      // ContributionForm
      'url': 'URL',
      'url.paste.description': 'Pega la URL de tu contribución (post de Twitter, commit de GitHub, etc.)',
      'description.optional': 'Descripción (Opcional)',
      'brief.description': 'Breve descripción de tu contribución...',
      'validation.rules': 'Reglas de Validación',
      'validation.rule.1': 'Las URLs deben ser públicas y accesibles',
      'validation.rule.2': 'Los posts de Twitter deben mencionar @QubicOfficial o #Qubic',
      'validation.rule.3': 'Los commits de GitHub deben estar en repositorios relacionados con Qubic',
      'validation.rule.4': 'Las entregas duplicadas serán rechazadas',
      'validation.rule.5': 'Cada tipo de contribución tiene un período de enfriamiento',
      
      // Analytics
      'your.performance': 'Tu Rendimiento',
      'weekly.average': 'Promedio Semanal',
      'best.week': 'Mejor Semana',
      'consistency.score': 'Puntuación de Consistencia',
      'total.streak': 'Racha Total',
      'monthly.goal': 'Meta Mensual',
      'target': 'Objetivo',
      'points.to.go': 'puntos por alcanzar',
      'days.remaining': 'días restantes',
      'detailed.analytics': 'Análisis Detallado',
      'points.unit': 'puntos',
      'days.unit': 'días',
    },
    fr: {
      'ambassador.platform': 'Plateforme d\'Ambassadeurs',
      'connect.wallet': 'Connecter le Portefeuille',
      'connected': 'Connecté',
      'connecting': 'Connexion...',
      'connect': 'Connecter',
      'dashboard': 'Tableau de Bord',
      'submit.contribution': 'Soumettre une Contribution',
      'leaderboard': 'Classement',
      'your.analytics': 'Vos Analyses',
      'settings': 'Paramètres',
      'help': 'Aide',
      'loading': 'Chargement...',
      'error': 'Erreur',
      'success': 'Succès',
      'cancel': 'Annuler',
      'save': 'Enregistrer',
      'delete': 'Supprimer',
      'edit': 'Modifier',
      'view': 'Voir',
      'close': 'Fermer',
      'submit': 'Soumettre',
      'back': 'Retour',
      'next': 'Suivant',
      'previous': 'Précédent',
      'welcome.back': 'Bon retour',
      'total.contributions': 'Contributions Totales',
      'total.points': 'Points Totaux',
      'rank': 'Rang',
      'recent.activity': 'Activité Récente',
      'no.activity': 'Aucune activité récente',
      'contribution.title': 'Soumettre Votre Contribution',
      'contribution.description': 'Partagez votre travail et gagnez des points',
      'contribution.type': 'Type de Contribution',
      'contribution.title.label': 'Titre',
      'contribution.title.placeholder': 'Entrez le titre de la contribution',
      'contribution.description.label': 'Description',
      'contribution.description.placeholder': 'Décrivez votre contribution',
      'contribution.url.label': 'URL (Optionnel)',
      'contribution.url.placeholder': 'https://example.com',
      'contribution.category': 'Catégorie',
      'contribution.category.content': 'Création de Contenu',
      'contribution.category.development': 'Développement',
      'contribution.category.community': 'Communauté',
      'contribution.category.translation': 'Traduction',
      'contribution.category.other': 'Autre',
      'leaderboard.title': 'Classement',
      'leaderboard.description': 'Meilleurs contributeurs ce mois-ci',
      'rank.position': 'Rang',
      'user': 'Utilisateur',
      'points': 'Points',
      'contributions': 'Contributions',
      'analytics.title': 'Vos Analyses',
      'analytics.description': 'Suivez vos performances et votre croissance',
      'analytics.overview': 'Aperçu',
      'analytics.contributions.chart': 'Contributions dans le Temps',
      'analytics.points.chart': 'Points Gagnés',
      'analytics.activity.chart': 'Carte de Chaleur d\'Activité',
      'blog.title': 'Dernières Mises à Jour',
      'blog.description': 'Restez informé des derniers développements de l\'équipe Qubic.',
      'blog.read.more': 'Lire Plus',
      'blog.published': 'Publié',
      'footer.copyright': '© 2025 Qubic Platform. Tous droits réservés.',
      'footer.privacy': 'Politique de Confidentialité',
      'footer.terms': 'Conditions de Service',
      'footer.version': 'Version 1.0.2',
      'language': 'Langue',
      'select.language': 'Sélectionner la Langue',
      'visitor.active.ambassadors': 'Ambassadeurs Actifs',
      'visitor.total.contributions': 'Contributions Totales',
      'visitor.growth.this.week': 'Croissance Cette Semaine',
      'visitor.this.week': 'Cette Semaine',
      'visitor.all.time': 'Tout le Temps',
      'visitor.last.activity': 'Dernière Activité',
      'visitor.about.program': 'À Propos du Programme d\'Ambassadeurs',
      'visitor.about.description': 'Le Programme d\'Ambassadeurs Qubic reconnaît et récompense les membres de la communauté qui contribuent activement à la croissance et au succès de l\'écosystème Qubic.',
      'visitor.join.community': 'Rejoindre la Communauté',
      'visitor.join.description': 'Intéressé à devenir Ambassadeur Qubic ? Connectez votre portefeuille pour explorer les opportunités et commencer à contribuer à l\'écosystème.',
      'visitor.why.join': 'Pourquoi rejoindre le programme ?',
      'visitor.why.join.description': 'Devenez membre de la communauté Qubic et gagnez des récompenses pour vos contributions',
      'visitor.community.building': 'Construction de Communauté',
      'visitor.community.building.description': 'Connectez-vous avec d\'autres ambassadeurs et développez la communauté Qubic grâce à du contenu engageant et des événements.',
      'visitor.track.performance': 'Suivi des Performances',
      'visitor.track.performance.description': 'Surveillez votre impact avec des analyses en temps réel et voyez comment vos contributions stimulent l\'engagement.',
      'visitor.earn.rewards': 'Gagner des Récompenses',
      'visitor.earn.rewards.description': 'Complétez des tâches et grimpez au classement pour gagner des points et de la reconnaissance dans la communauté.',
      'visitor.connect.wallet.step': 'Connectez votre portefeuille Qubic',
      'visitor.verification.step': 'Complétez le processus de vérification',
      'visitor.start.earning.step': 'Commencez à gagner des points pour vos contributions',
      'visitor.twitter.badge': '🐦 Twitter',
      'visitor.github.badge': '💻 GitHub',
      'visitor.content.badge': '📝 Contenu',
      'visitor.social.media.engagement': 'Engagement sur les réseaux sociaux',
      'visitor.technical.contributions': 'Contributions techniques',
      'visitor.educational.content': 'Création de contenu éducatif',
      'leaderboard.this.week': 'Cette Semaine',
      'leaderboard.all.time': 'Tout le Temps',
      'leaderboard.last.activity': 'Dernière Activité',
      'leaderboard.top.contributor': 'Meilleur Contributeur',
      'leaderboard.active.contributor': 'Contributeur Actif',
      'leaderboard.rising.star': 'Étoile Montante',
      'leaderboard.ambassador': 'Ambassadeur',
      'leaderboard.just.now': 'À l\'instant',
      'leaderboard.hours.ago': 'heures',
      'leaderboard.days.ago': 'jours',
      'recent.activity.title': 'Activité Récente',
      'recent.activity.no.activity': 'Aucune activité récente trouvée.',
      'recent.activity.start.contributing': 'Commencez à contribuer pour voir votre activité ici !',
      'recent.activity.points': 'point',
      'recent.activity.points.plural': 'points',
      
      // Dashboard Stats
      'from.last.week': 'depuis la semaine dernière',
      'this.week': 'cette semaine',
      'up.positions': 'En hausse',
      'positions': 'positions',
      'points.this.week': 'points cette semaine',
      
      // Charts
      'your.contribution.trend': 'Votre Tendance de Contributions',
      'contribution.types': 'Types de Contributions',
      'your.points': 'Vos Points',
      'community.average': 'Moyenne de la Communauté',
      
      // ContributionForm
      'url': 'URL',
      'url.paste.description': 'Collez l\'URL de votre contribution (post Twitter, commit GitHub, etc.)',
      'description.optional': 'Description (Optionnel)',
      'brief.description': 'Brève description de votre contribution...',
      'validation.rules': 'Règles de Validation',
      'validation.rule.1': 'Les URLs doivent être publiques et accessibles',
      'validation.rule.2': 'Les posts Twitter doivent mentionner @QubicOfficial ou #Qubic',
      'validation.rule.3': 'Les commits GitHub doivent être dans des dépôts liés à Qubic',
      'validation.rule.4': 'Les soumissions en double seront rejetées',
      'validation.rule.5': 'Chaque type de contribution a une période de récupération',
      
      // Analytics
      'your.performance': 'Vos Performances',
      'weekly.average': 'Moyenne Hebdomadaire',
      'best.week': 'Meilleure Semaine',
      'consistency.score': 'Score de Cohérence',
      'total.streak': 'Série Totale',
      'monthly.goal': 'Objectif Mensuel',
      'target': 'Cible',
      'points.to.go': 'points à atteindre',
      'days.remaining': 'jours restants',
      'detailed.analytics': 'Analyses Détaillées',
      'points.unit': 'points',
      'days.unit': 'jours',
    },
    it: {
      'ambassador.platform': 'Piattaforma Ambasciatori',
      'connect.wallet': 'Connetti Portafoglio',
      'connected': 'Connesso',
      'connecting': 'Connessione...',
      'connect': 'Connetti',
      'dashboard': 'Dashboard',
      'submit.contribution': 'Invia Contributo',
      'leaderboard': 'Classifica',
      'your.analytics': 'Le Tue Analisi',
      'settings': 'Impostazioni',
      'help': 'Aiuto',
      'loading': 'Caricamento...',
      'error': 'Errore',
      'success': 'Successo',
      'cancel': 'Annulla',
      'save': 'Salva',
      'delete': 'Elimina',
      'edit': 'Modifica',
      'view': 'Visualizza',
      'close': 'Chiudi',
      'submit': 'Invia',
      'back': 'Indietro',
      'next': 'Avanti',
      'previous': 'Precedente',
      'welcome.back': 'Bentornato',
      'total.contributions': 'Contributi Totali',
      'total.points': 'Punti Totali',
      'rank': 'Posizione',
      'recent.activity': 'Attività Recente',
      'no.activity': 'Nessuna attività recente',
      'contribution.title': 'Invia Il Tuo Contributo',
      'contribution.description': 'Condividi il tuo lavoro e guadagna punti',
      'contribution.type': 'Tipo di Contributo',
      'contribution.title.label': 'Titolo',
      'contribution.title.placeholder': 'Inserisci il titolo del contributo',
      'contribution.description.label': 'Descrizione',
      'contribution.description.placeholder': 'Descrivi il tuo contributo',
      'contribution.url.label': 'URL (Opzionale)',
      'contribution.url.placeholder': 'https://example.com',
      'contribution.category': 'Categoria',
      'contribution.category.content': 'Creazione Contenuti',
      'contribution.category.development': 'Sviluppo',
      'contribution.category.community': 'Comunità',
      'contribution.category.translation': 'Traduzione',
      'contribution.category.other': 'Altro',
      'leaderboard.title': 'Classifica',
      'leaderboard.description': 'Migliori contributori questo mese',
      'rank.position': 'Posizione',
      'user': 'Utente',
      'points': 'Punti',
      'contributions': 'Contributi',
      'analytics.title': 'Le Tue Analisi',
      'analytics.description': 'Traccia le tue prestazioni e crescita',
      'analytics.overview': 'Panoramica',
      'analytics.contributions.chart': 'Contributi nel Tempo',
      'analytics.points.chart': 'Punti Guadagnati',
      'analytics.activity.chart': 'Mappa Termica Attività',
      'blog.title': 'Ultimi Aggiornamenti',
      'blog.description': 'Rimani aggiornato sugli ultimi sviluppi del team Qubic.',
      'blog.read.more': 'Leggi di Più',
      'blog.published': 'Pubblicato',
      'footer.copyright': '© 2025 Qubic Platform. Tutti i diritti riservati.',
      'footer.privacy': 'Politica sulla Privacy',
      'footer.terms': 'Termini di Servizio',
      'footer.version': 'Versione 1.0.2',
      'language': 'Lingua',
      'select.language': 'Seleziona Lingua',
      'visitor.active.ambassadors': 'Ambasciatori Attivi',
      'visitor.total.contributions': 'Contributi Totali',
      'visitor.growth.this.week': 'Crescita Questa Settimana',
      'visitor.this.week': 'Questa Settimana',
      'visitor.all.time': 'Tutto il Tempo',
      'visitor.last.activity': 'Ultima Attività',
      'visitor.about.program': 'Informazioni sul Programma Ambasciatori',
      'visitor.about.description': 'Il Programma Ambasciatori Qubic riconosce e premia i membri della comunità che contribuiscono attivamente alla crescita e al successo dell\'ecosistema Qubic.',
      'visitor.join.community': 'Unisciti alla Comunità',
      'visitor.join.description': 'Interessato a diventare Ambasciatore Qubic? Connetti il tuo portafoglio per esplorare le opportunità e iniziare a contribuire all\'ecosistema.',
      'visitor.why.join': 'Perché unirsi al programma?',
      'visitor.why.join.description': 'Diventa parte della comunità Qubic e guadagna ricompense per i tuoi contributi',
      'visitor.community.building': 'Costruzione della Comunità',
      'visitor.community.building.description': 'Connettiti con altri ambasciatori e fai crescere la comunità Qubic attraverso contenuti coinvolgenti ed eventi.',
      'visitor.track.performance': 'Monitoraggio delle Prestazioni',
      'visitor.track.performance.description': 'Monitora il tuo impatto con analisi in tempo reale e vedi come i tuoi contributi stimolano l\'engagement.',
      'visitor.earn.rewards': 'Guadagna Ricompense',
      'visitor.earn.rewards.description': 'Completa le attività e sali nella classifica per guadagnare punti e riconoscimento nella comunità.',
      'visitor.connect.wallet.step': 'Connetti il tuo portafoglio Qubic',
      'visitor.verification.step': 'Completa il processo di verifica',
      'visitor.start.earning.step': 'Inizia a guadagnare punti per i contributi',
      'visitor.twitter.badge': '🐦 Twitter',
      'visitor.github.badge': '💻 GitHub',
      'visitor.content.badge': '📝 Contenuto',
      'visitor.social.media.engagement': 'Engagement sui social media',
      'visitor.technical.contributions': 'Contributi tecnici',
      'visitor.educational.content': 'Creazione di contenuti educativi',
      'leaderboard.this.week': 'Questa Settimana',
      'leaderboard.all.time': 'Tutto il Tempo',
      'leaderboard.last.activity': 'Ultima Attività',
      'leaderboard.top.contributor': 'Miglior Contributore',
      'leaderboard.active.contributor': 'Contributore Attivo',
      'leaderboard.rising.star': 'Stella Nascente',
      'leaderboard.ambassador': 'Ambasciatore',
      'leaderboard.just.now': 'Proprio ora',
      'leaderboard.hours.ago': 'ore fa',
      'leaderboard.days.ago': 'giorni fa',
      'recent.activity.title': 'Attività Recente',
      'recent.activity.no.activity': 'Nessuna attività recente trovata.',
      'recent.activity.start.contributing': 'Inizia a contribuire per vedere la tua attività qui!',
      'recent.activity.points': 'punto',
      'recent.activity.points.plural': 'punti',
      
      // Dashboard Stats
      'from.last.week': 'dalla settimana scorsa',
      'this.week': 'questa settimana',
      'up.positions': 'Su di',
      'positions': 'posizioni',
      'points.this.week': 'punti questa settimana',
      
      // Charts
      'your.contribution.trend': 'La Tua Tendenza di Contributi',
      'contribution.types': 'Tipi di Contributi',
      'your.points': 'I Tuoi Punti',
      'community.average': 'Media della Comunità',
      
      // ContributionForm
      'url': 'URL',
      'url.paste.description': 'Incolla l\'URL del tuo contributo (post Twitter, commit GitHub, ecc.)',
      'description.optional': 'Descrizione (Opzionale)',
      'brief.description': 'Breve descrizione del tuo contributo...',
      'validation.rules': 'Regole di Validazione',
      'validation.rule.1': 'Gli URL devono essere pubblici e accessibili',
      'validation.rule.2': 'I post Twitter devono menzionare @QubicOfficial o #Qubic',
      'validation.rule.3': 'I commit GitHub devono essere in repository correlati a Qubic',
      'validation.rule.4': 'Le sottomissioni duplicate saranno respinte',
      'validation.rule.5': 'Ogni tipo di contributo ha un periodo di raffreddamento',
      
      // Analytics
      'your.performance': 'Le Tue Prestazioni',
      'weekly.average': 'Media Settimanale',
      'best.week': 'Migliore Settimana',
      'consistency.score': 'Punteggio di Coerenza',
      'total.streak': 'Striscia Totale',
      'monthly.goal': 'Obiettivo Mensile',
      'target': 'Obiettivo',
      'points.to.go': 'punti da raggiungere',
      'days.remaining': 'giorni rimanenti',
      'detailed.analytics': 'Analisi Dettagliate',
      'points.unit': 'punti',
      'days.unit': 'giorni',
    },
    nl: {
      'ambassador.platform': 'Ambassadeur Platform',
      'connect.wallet': 'Wallet Verbinden',
      'connected': 'Verbonden',
      'connecting': 'Verbinden...',
      'connect': 'Verbinden',
      'dashboard': 'Dashboard',
      'submit.contribution': 'Bijdrage Indienen',
      'leaderboard': 'Ranglijst',
      'your.analytics': 'Jouw Analyses',
      'settings': 'Instellingen',
      'help': 'Help',
      'loading': 'Laden...',
      'error': 'Fout',
      'success': 'Succes',
      'cancel': 'Annuleren',
      'save': 'Opslaan',
      'delete': 'Verwijderen',
      'edit': 'Bewerken',
      'view': 'Bekijken',
      'close': 'Sluiten',
      'submit': 'Indienen',
      'back': 'Terug',
      'next': 'Volgende',
      'previous': 'Vorige',
      'welcome.back': 'Welkom terug',
      'total.contributions': 'Totale Bijdragen',
      'total.points': 'Totale Punten',
      'rank': 'Rang',
      'recent.activity': 'Recente Activiteit',
      'no.activity': 'Geen recente activiteit',
      'contribution.title': 'Dien Je Bijdrage In',
      'contribution.description': 'Deel je werk en verdien punten',
      'contribution.type': 'Bijdrage Type',
      'contribution.title.label': 'Titel',
      'contribution.title.placeholder': 'Voer bijdrage titel in',
      'contribution.description.label': 'Beschrijving',
      'contribution.description.placeholder': 'Beschrijf je bijdrage',
      'contribution.url.label': 'URL (Optioneel)',
      'contribution.url.placeholder': 'https://example.com',
      'contribution.category': 'Categorie',
      'contribution.category.content': 'Content Creatie',
      'contribution.category.development': 'Ontwikkeling',
      'contribution.category.community': 'Gemeenschap',
      'contribution.category.translation': 'Vertaling',
      'contribution.category.other': 'Andere',
      'leaderboard.title': 'Ranglijst',
      'leaderboard.description': 'Top bijdragers deze maand',
      'rank.position': 'Rang',
      'user': 'Gebruiker',
      'points': 'Punten',
      'contributions': 'Bijdragen',
      'analytics.title': 'Jouw Analyses',
      'analytics.description': 'Volg je prestaties en groei',
      'analytics.overview': 'Overzicht',
      'analytics.contributions.chart': 'Bijdragen in de Tijd',
      'analytics.points.chart': 'Verdiende Punten',
      'analytics.activity.chart': 'Activiteit Warmtekaart',
      'blog.title': 'Laatste Updates',
      'blog.description': 'Blijf op de hoogte van de laatste ontwikkelingen van het Qubic-team.',
      'blog.read.more': 'Lees Meer',
      'blog.published': 'Gepubliceerd',
      'footer.copyright': '© 2025 Qubic Platform. Alle rechten voorbehouden.',
      'footer.privacy': 'Privacybeleid',
      'footer.terms': 'Servicevoorwaarden',
      'footer.version': 'Versie 1.0.2',
      'language': 'Taal',
      'select.language': 'Selecteer Taal',
      'visitor.active.ambassadors': 'Actieve Ambassadeurs',
      'visitor.total.contributions': 'Totale Bijdragen',
      'visitor.growth.this.week': 'Groei Deze Week',
      'visitor.this.week': 'Deze Week',
      'visitor.all.time': 'Alle Tijd',
      'visitor.last.activity': 'Laatste Activiteit',
      'visitor.about.program': 'Over het Ambassadeur Programma',
      'visitor.about.description': 'Het Qubic Ambassadeur Programma erkent en beloont community-leden die actief bijdragen aan de groei en het succes van het Qubic ecosysteem.',
      'visitor.join.community': 'Word Lid van de Community',
      'visitor.join.description': 'Geïnteresseerd in het worden van een Qubic Ambassadeur? Verbind je wallet om kansen te verkennen en te beginnen met bijdragen aan het ecosysteem.',
      'visitor.why.join': 'Waarom lid worden van het programma?',
      'visitor.why.join.description': 'Word onderdeel van de Qubic community en verdien beloningen voor je bijdragen',
      'visitor.community.building': 'Community Bouwen',
      'visitor.community.building.description': 'Verbind met andere ambassadeurs en laat de Qubic community groeien door boeiende content en evenementen.',
      'visitor.track.performance': 'Prestaties Bijhouden',
      'visitor.track.performance.description': 'Monitor je impact met real-time analyses en zie hoe je bijdragen engagement stimuleren.',
      'visitor.earn.rewards': 'Beloningen Verdienen',
      'visitor.earn.rewards.description': 'Voltooi taken en klim in de ranglijst om punten en erkenning in de community te verdienen.',
      'visitor.connect.wallet.step': 'Verbind je Qubic wallet',
      'visitor.verification.step': 'Voltooi het verificatieproces',
      'visitor.start.earning.step': 'Begin met het verdienen van punten voor bijdragen',
      'visitor.twitter.badge': '🐦 Twitter',
      'visitor.github.badge': '💻 GitHub',
      'visitor.content.badge': '📝 Content',
      'visitor.social.media.engagement': 'Social media engagement',
      'visitor.technical.contributions': 'Technische bijdragen',
      'visitor.educational.content': 'Educatieve content maken',
      'leaderboard.this.week': 'Deze Week',
      'leaderboard.all.time': 'Alle Tijd',
      'leaderboard.last.activity': 'Laatste Activiteit',
      'leaderboard.top.contributor': 'Top Bijdrager',
      'leaderboard.active.contributor': 'Actieve Bijdrager',
      'leaderboard.rising.star': 'Opkomende Ster',
      'leaderboard.ambassador': 'Ambassadeur',
      'leaderboard.just.now': 'Zojuist',
      'leaderboard.hours.ago': 'uur geleden',
      'leaderboard.days.ago': 'dagen geleden',
      'recent.activity.title': 'Recente Activiteit',
      'recent.activity.no.activity': 'Geen recente activiteit gevonden.',
      'recent.activity.start.contributing': 'Begin met bijdragen om je activiteit hier te zien!',
      'recent.activity.points': 'punt',
      'recent.activity.points.plural': 'punten',
      
      // Dashboard Stats  
      'from.last.week': 'van vorige week',
      'this.week': 'deze week',
      'up.positions': 'Omhoog',
      'positions': 'posities',
      'points.this.week': 'punten deze week',
      
      // Charts
      'your.contribution.trend': 'Jouw Bijdrage Trend',
      'contribution.types': 'Bijdrage Types',
      'your.points': 'Jouw Punten',
      'community.average': 'Community Gemiddelde',
      
      // ContributionForm
      'url': 'URL',
      'url.paste.description': 'Plak de URL van je bijdrage (Twitter post, GitHub commit, etc.)',
      'description.optional': 'Beschrijving (Optioneel)',
      'brief.description': 'Korte beschrijving van je bijdrage...',
      'validation.rules': 'Validatieregels',
      'validation.rule.1': 'URLs moeten openbaar en toegankelijk zijn',
      'validation.rule.2': 'Twitter posts moeten @QubicOfficial of #Qubic vermelden',
      'validation.rule.3': 'GitHub commits moeten in Qubic-gerelateerde repositories zijn',
      'validation.rule.4': 'Dubbele inzendingen worden afgewezen',
      'validation.rule.5': 'Elk bijdragetype heeft een afkoelperiode',
      
      // Analytics
      'your.performance': 'Jouw Prestaties',
      'weekly.average': 'Wekelijks Gemiddelde',
      'best.week': 'Beste Week',
      'consistency.score': 'Consistentie Score',
      'total.streak': 'Totale Reeks',
      'monthly.goal': 'Maandelijks Doel',
      'target': 'Doel',
      'points.to.go': 'punten te gaan',
      'days.remaining': 'dagen over',
      'detailed.analytics': 'Gedetailleerde Analytics',
      'points.unit': 'punten',
      'days.unit': 'dagen',
    },
    pt: {
      'ambassador.platform': 'Plataforma de Embaixadores',
      'connect.wallet': 'Conectar Carteira',
      'connected': 'Conectado',
      'connecting': 'Conectando...',
      'connect': 'Conectar',
      'dashboard': 'Painel de Controle',
      'submit.contribution': 'Enviar Contribuição',
      'leaderboard': 'Classificação',
      'your.analytics': 'Suas Análises',
      'settings': 'Configurações',
      'help': 'Ajuda',
      'loading': 'Carregando...',
      'error': 'Erro',
      'success': 'Sucesso',
      'cancel': 'Cancelar',
      'save': 'Salvar',
      'delete': 'Excluir',
      'edit': 'Editar',
      'view': 'Visualizar',
      'close': 'Fechar',
      'submit': 'Enviar',
      'back': 'Voltar',
      'next': 'Próximo',
      'previous': 'Anterior',
      'welcome.back': 'Bem-vindo de volta',
      'total.contributions': 'Contribuições Totais',
      'total.points': 'Pontos Totais',
      'rank': 'Posição',
      'recent.activity': 'Atividade Recente',
      'no.activity': 'Nenhuma atividade recente',
      'contribution.title': 'Enviar Sua Contribuição',
      'contribution.description': 'Compartilhe seu trabalho e ganhe pontos',
      'contribution.type': 'Tipo de Contribuição',
      'contribution.title.label': 'Título',
      'contribution.title.placeholder': 'Digite o título da contribuição',
      'contribution.description.label': 'Descrição',
      'contribution.description.placeholder': 'Descreva sua contribuição',
      'contribution.url.label': 'URL (Opcional)',
      'contribution.url.placeholder': 'https://example.com',
      'contribution.category': 'Categoria',
      'contribution.category.content': 'Criação de Conteúdo',
      'contribution.category.development': 'Desenvolvimento',
      'contribution.category.community': 'Comunidade',
      'contribution.category.translation': 'Tradução',
      'contribution.category.other': 'Outro',
      'leaderboard.title': 'Classificação',
      'leaderboard.description': 'Principais contribuidores este mês',
      'rank.position': 'Posição',
      'user': 'Usuário',
      'points': 'Pontos',
      'contributions': 'Contribuições',
      'analytics.title': 'Suas Análises',
      'analytics.description': 'Acompanhe seu desempenho e crescimento',
      'analytics.overview': 'Visão Geral',
      'analytics.contributions.chart': 'Contribuições ao Longo do Tempo',
      'analytics.points.chart': 'Pontos Ganhos',
      'analytics.activity.chart': 'Mapa de Calor de Atividade',
      'blog.title': 'Últimas Atualizações',
      'blog.description': 'Mantenha-se informado sobre os últimos desenvolvimentos da equipe Qubic.',
      'blog.read.more': 'Ler Mais',
      'blog.published': 'Publicado',
      'footer.copyright': '© 2025 Qubic Platform. Todos os direitos reservados.',
      'footer.privacy': 'Política de Privacidade',
      'footer.terms': 'Termos de Serviço',
      'footer.version': 'Versão 1.0.2',
      'language': 'Idioma',
      'select.language': 'Selecionar Idioma',
      'visitor.active.ambassadors': 'Embaixadores Ativos',
      'visitor.total.contributions': 'Contribuições Totais',
      'visitor.growth.this.week': 'Crescimento Esta Semana',
      'visitor.this.week': 'Esta Semana',
      'visitor.all.time': 'Todo o Tempo',
      'visitor.last.activity': 'Última Atividade',
      'visitor.about.program': 'Sobre o Programa de Embaixadores',
      'visitor.about.description': 'O Programa de Embaixadores Qubic reconhece e recompensa membros da comunidade que contribuem ativamente para o crescimento e sucesso do ecossistema Qubic.',
      'visitor.join.community': 'Junte-se à Comunidade',
      'visitor.join.description': 'Interessado em se tornar um Embaixador Qubic? Conecte sua carteira para explorar oportunidades e começar a contribuir para o ecossistema.',
      'visitor.why.join': 'Por que se juntar ao programa?',
      'visitor.why.join.description': 'Torne-se parte da comunidade Qubic e ganhe recompensas por suas contribuições',
      'visitor.community.building': 'Construção da Comunidade',
      'visitor.community.building.description': 'Conecte-se com outros embaixadores e faça a comunidade Qubic crescer através de conteúdo envolvente e eventos.',
      'visitor.track.performance': 'Acompanhar Desempenho',
      'visitor.track.performance.description': 'Monitore seu impacto com análises em tempo real e veja como suas contribuições impulsionam o engajamento.',
      'visitor.earn.rewards': 'Ganhar Recompensas',
      'visitor.earn.rewards.description': 'Complete tarefas e suba na classificação para ganhar pontos e reconhecimento na comunidade.',
      'visitor.connect.wallet.step': 'Conecte sua carteira Qubic',
      'visitor.verification.step': 'Complete o processo de verificação',
      'visitor.start.earning.step': 'Comece a ganhar pontos por contribuições',
      'visitor.twitter.badge': '🐦 Twitter',
      'visitor.github.badge': '💻 GitHub',
      'visitor.content.badge': '📝 Conteúdo',
      'visitor.social.media.engagement': 'Engajamento em redes sociais',
      'visitor.technical.contributions': 'Contribuições técnicas',
      'visitor.educational.content': 'Criação de conteúdo educacional',
      'leaderboard.this.week': 'Esta Semana',
      'leaderboard.all.time': 'Todo o Tempo',
      'leaderboard.last.activity': 'Última Atividade',
      'leaderboard.top.contributor': 'Melhor Contribuidor',
      'leaderboard.active.contributor': 'Contribuidor Ativo',
      'leaderboard.rising.star': 'Estrela em Ascensão',
      'leaderboard.ambassador': 'Embaixador',
      'leaderboard.just.now': 'Agora mesmo',
      'leaderboard.hours.ago': 'horas atrás',
      'leaderboard.days.ago': 'dias atrás',
      'recent.activity.title': 'Atividade Recente',
      'recent.activity.no.activity': 'Nenhuma atividade recente encontrada.',
      'recent.activity.start.contributing': 'Comece a contribuir para ver sua atividade aqui!',
      'recent.activity.points': 'ponto',
      'recent.activity.points.plural': 'pontos',
      
      // Dashboard Stats
      'from.last.week': 'da semana passada',
      'this.week': 'esta semana',
      'up.positions': 'Subiu',
      'positions': 'posições',
      'points.this.week': 'pontos esta semana',
      
      // Charts
      'your.contribution.trend': 'Sua Tendência de Contribuições',
      'contribution.types': 'Tipos de Contribuição',
      'your.points': 'Seus Pontos',
      'community.average': 'Média da Comunidade',
      
      // ContributionForm
      'url': 'URL',
      'url.paste.description': 'Cole a URL da sua contribuição (post do Twitter, commit do GitHub, etc.)',
      'description.optional': 'Descrição (Opcional)',
      'brief.description': 'Breve descrição da sua contribuição...',
      'validation.rules': 'Regras de Validação',
      'validation.rule.1': 'URLs devem ser públicas e acessíveis',
      'validation.rule.2': 'Posts do Twitter devem mencionar @QubicOfficial ou #Qubic',
      'validation.rule.3': 'Commits do GitHub devem estar em repositórios relacionados ao Qubic',
      'validation.rule.4': 'Submissões duplicadas serão rejeitadas',
      'validation.rule.5': 'Cada tipo de contribuição tem um período de espera',
      
      // Analytics
      'your.performance': 'Seu Desempenho',
      'weekly.average': 'Média Semanal',
      'best.week': 'Melhor Semana',
      'consistency.score': 'Pontuação de Consistência',
      'total.streak': 'Sequência Total',
      'monthly.goal': 'Meta Mensal',
      'target': 'Meta',
      'points.to.go': 'pontos para alcançar',
      'days.remaining': 'dias restantes',
      'detailed.analytics': 'Análises Detalhadas',
      'points.unit': 'pontos',
      'days.unit': 'dias',
    },
    tr: {
      'ambassador.platform': 'Büyükelçi Platformu',
      'connect.wallet': 'Cüzdan Bağla',
      'connected': 'Bağlandı',
      'connecting': 'Bağlanıyor...',
      'connect': 'Bağlan',
      'dashboard': 'Gösterge Paneli',
      'submit.contribution': 'Katkı Gönder',
      'leaderboard': 'Lider Tablosu',
      'your.analytics': 'Analizleriniz',
      'settings': 'Ayarlar',
      'help': 'Yardım',
      'loading': 'Yükleniyor...',
      'error': 'Hata',
      'success': 'Başarılı',
      'cancel': 'İptal',
      'save': 'Kaydet',
      'delete': 'Sil',
      'edit': 'Düzenle',
      'view': 'Görüntüle',
      'close': 'Kapat',
      'submit': 'Gönder',
      'back': 'Geri',
      'next': 'İleri',
      'previous': 'Önceki',
      'welcome.back': 'Tekrar hoş geldiniz',
      'total.contributions': 'Toplam Katkılar',
      'total.points': 'Toplam Puanlar',
      'rank': 'Sıra',
      'recent.activity': 'Son Aktiviteler',
      'no.activity': 'Son aktivite yok',
      'contribution.title': 'Katkınızı Gönderin',
      'contribution.description': 'Çalışmanızı paylaşın ve puan kazanın',
      'contribution.type': 'Katkı Türü',
      'contribution.title.label': 'Başlık',
      'contribution.title.placeholder': 'Katkı başlığını girin',
      'contribution.description.label': 'Açıklama',
      'contribution.description.placeholder': 'Katkınızı açıklayın',
      'contribution.url.label': 'URL (İsteğe Bağlı)',
      'contribution.url.placeholder': 'https://example.com',
      'contribution.category': 'Kategori',
      'contribution.category.content': 'İçerik Oluşturma',
      'contribution.category.development': 'Geliştirme',
      'contribution.category.community': 'Topluluk',
      'contribution.category.translation': 'Çeviri',
      'contribution.category.other': 'Diğer',
      'leaderboard.title': 'Lider Tablosu',
      'leaderboard.description': 'Bu ayın en iyi katkıda bulunanları',
      'rank.position': 'Sıra',
      'user': 'Kullanıcı',
      'points': 'Puanlar',
      'contributions': 'Katkılar',
      'analytics.title': 'Analizleriniz',
      'analytics.description': 'Performansınızı ve büyümenizi takip edin',
      'analytics.overview': 'Genel Bakış',
      'analytics.contributions.chart': 'Zaman İçinde Katkılar',
      'analytics.points.chart': 'Kazanılan Puanlar',
      'analytics.activity.chart': 'Aktivite Isı Haritası',
      'blog.title': 'Son Güncellemeler',
      'blog.description': 'Qubic ekibinin en son gelişmelerinden haberdar olun.',
      'blog.read.more': 'Devamını Oku',
      'blog.published': 'Yayınlandı',
      'footer.copyright': '© 2025 Qubic Platform. Tüm hakları saklıdır.',
      'footer.privacy': 'Gizlilik Politikası',
      'footer.terms': 'Hizmet Şartları',
      'footer.version': 'Sürüm 1.0.2',
      'language': 'Dil',
      'select.language': 'Dil Seçin',
      'visitor.active.ambassadors': 'Aktif Büyükelçiler',
      'visitor.total.contributions': 'Toplam Katkılar',
      'visitor.growth.this.week': 'Bu Hafta Büyüme',
      'visitor.this.week': 'Bu Hafta',
      'visitor.all.time': 'Tüm Zamanlar',
      'visitor.last.activity': 'Son Aktivite',
      'visitor.about.program': 'Büyükelçi Programı Hakkında',
      'visitor.about.description': 'Qubic Büyükelçi Programı, Qubic ekosisteminin büyümesine ve başarısına aktif olarak katkıda bulunan topluluk üyelerini tanır ve ödüllendirir.',
      'visitor.join.community': 'Topluluğa Katıl',
      'visitor.join.description': 'Qubic Büyükelçisi olmak ister misiniz? Fırsatları keşfetmek ve ekosisteme katkıda bulunmaya başlamak için cüzdanınızı bağlayın.',
      'visitor.why.join': 'Neden programa katılmalı?',
      'visitor.why.join.description': 'Qubic topluluğunun bir parçası olun ve katkılarınız için ödüller kazanın',
      'visitor.community.building': 'Topluluk İnşası',
      'visitor.community.building.description': 'Diğer büyükelçilerle bağlantı kurun ve ilgi çekici içerik ve etkinliklerle Qubic topluluğunu büyütün.',
      'visitor.track.performance': 'Performans Takibi',
      'visitor.track.performance.description': 'Gerçek zamanlı analizlerle etkinizi izleyin ve katkılarınızın etkileşimi nasıl artırdığını görün.',
      'visitor.earn.rewards': 'Ödüller Kazan',
      'visitor.earn.rewards.description': 'Görevleri tamamlayın ve toplulukta puan ve tanınma kazanmak için sıralamada yükselin.',
      'visitor.connect.wallet.step': 'Qubic cüzdanınızı bağlayın',
      'visitor.verification.step': 'Doğrulama sürecini tamamlayın',
      'visitor.start.earning.step': 'Katkılar için puan kazanmaya başlayın',
      'visitor.twitter.badge': '🐦 Twitter',
      'visitor.github.badge': '💻 GitHub',
      'visitor.content.badge': '📝 İçerik',
      'visitor.social.media.engagement': 'Sosyal medya etkileşimi',
      'visitor.technical.contributions': 'Teknik katkılar',
      'visitor.educational.content': 'Eğitici içerik oluşturma',
      'leaderboard.this.week': 'Bu Hafta',
      'leaderboard.all.time': 'Tüm Zamanlar',
      'leaderboard.last.activity': 'Son Aktivite',
      'leaderboard.top.contributor': 'En İyi Katkıda Bulunan',
      'leaderboard.active.contributor': 'Aktif Katkıda Bulunan',
      'leaderboard.rising.star': 'Yükselen Yıldız',
      'leaderboard.ambassador': 'Büyükelçi',
      'leaderboard.just.now': 'Az önce',
      'leaderboard.hours.ago': 'saat önce',
      'leaderboard.days.ago': 'gün önce',
      'recent.activity.title': 'Son Aktiviteler',
      'recent.activity.no.activity': 'Son aktivite bulunamadı.',
      'recent.activity.start.contributing': 'Aktivitelerinizi burada görmek için katkıda bulunmaya başlayın!',
      'recent.activity.points': 'puan',
      'recent.activity.points.plural': 'puan',
      
      // Dashboard Stats
      'from.last.week': 'geçen haftadan',
      'this.week': 'bu hafta',
      'up.positions': 'Yukarı',
      'positions': 'pozisyon',
      'points.this.week': 'puan bu hafta',
      
      // Charts
      'your.contribution.trend': 'Katkı Trendiniz',
      'contribution.types': 'Katkı Türleri',
      'your.points': 'Puanlarınız',
      'community.average': 'Topluluk Ortalaması',
      
      // ContributionForm
      'url': 'URL',
      'url.paste.description': 'Katkınızın URL\'sini yapıştırın (Twitter gönderisi, GitHub commit\'i, vb.)',
      'description.optional': 'Açıklama (İsteğe Bağlı)',
      'brief.description': 'Katkınızın kısa açıklaması...',
      'validation.rules': 'Doğrulama Kuralları',
      'validation.rule.1': 'URL\'ler halka açık ve erişilebilir olmalıdır',
      'validation.rule.2': 'Twitter gönderileri @QubicOfficial veya #Qubic\'ten bahsetmelidir',
      'validation.rule.3': 'GitHub commit\'leri Qubic ile ilgili depolarda olmalıdır',
      'validation.rule.4': 'Yinelenen gönderiler reddedilecektir',
      'validation.rule.5': 'Her katkı türünün bir bekleme süresi vardır',
      
      // Analytics
      'your.performance': 'Performansınız',
      'weekly.average': 'Haftalık Ortalama',
      'best.week': 'En İyi Hafta',
      'consistency.score': 'Tutarlılık Puanı',
      'total.streak': 'Toplam Seri',
      'monthly.goal': 'Aylık Hedef',
      'target': 'Hedef',
      'points.to.go': 'ulaşılacak puan',
      'days.remaining': 'kalan gün',
      'detailed.analytics': 'Detaylı Analizler',
      'points.unit': 'puan',
      'days.unit': 'gün',
    },
    zh: {
      'ambassador.platform': '大使平台',
      'connect.wallet': '连接钱包',
      'connected': '已连接',
      'connecting': '连接中...',
      'connect': '连接',
      'dashboard': '仪表板',
      'submit.contribution': '提交贡献',
      'leaderboard': '排行榜',
      'your.analytics': '您的分析',
      'settings': '设置',
      'help': '帮助',
      'loading': '加载中...',
      'error': '错误',
      'success': '成功',
      'cancel': '取消',
      'save': '保存',
      'delete': '删除',
      'edit': '编辑',
      'view': '查看',
      'close': '关闭',
      'submit': '提交',
      'back': '返回',
      'next': '下一步',
      'previous': '上一步',
      'welcome.back': '欢迎回来',
      'total.contributions': '总贡献',
      'total.points': '总积分',
      'rank': '排名',
      'recent.activity': '最近活动',
      'no.activity': '暂无最近活动',
      'contribution.title': '提交您的贡献',
      'contribution.description': '分享您的工作并获得积分',
      'contribution.type': '贡献类型',
      'contribution.title.label': '标题',
      'contribution.title.placeholder': '输入贡献标题',
      'contribution.description.label': '描述',
      'contribution.description.placeholder': '描述您的贡献',
      'contribution.url.label': 'URL（可选）',
      'contribution.url.placeholder': 'https://example.com',
      'contribution.category': '类别',
      'contribution.category.content': '内容创作',
      'contribution.category.development': '开发',
      'contribution.category.community': '社区',
      'contribution.category.translation': '翻译',
      'contribution.category.other': '其他',
      'leaderboard.title': '排行榜',
      'leaderboard.description': '本月最佳贡献者',
      'rank.position': '排名',
      'user': '用户',
      'points': '积分',
      'contributions': '贡献',
      'analytics.title': '您的分析',
      'analytics.description': '跟踪您的表现和成长',
      'analytics.overview': '概览',
      'analytics.contributions.chart': '贡献时间线',
      'analytics.points.chart': '获得积分',
      'analytics.activity.chart': '活动热力图',
      'blog.title': '最新更新',
      'blog.description': '了解Qubic团队的最新发展动态。',
      'blog.read.more': '阅读更多',
      'blog.published': '已发布',
      'footer.copyright': '© 2025 Qubic Platform. 保留所有权利。',
      'footer.privacy': '隐私政策',
      'footer.terms': '服务条款',
      'footer.version': '版本 1.0.2',
      'language': '语言',
      'select.language': '选择语言',
      'visitor.active.ambassadors': '活跃大使',
      'visitor.total.contributions': '总贡献',
      'visitor.growth.this.week': '本周增长',
      'visitor.this.week': '本周',
      'visitor.all.time': '所有时间',
      'visitor.last.activity': '最后活动',
      'visitor.about.program': '关于大使计划',
      'visitor.about.description': 'Qubic大使计划认可并奖励积极为Qubic生态系统增长和成功做出贡献的社区成员。',
      'visitor.join.community': '加入社区',
      'visitor.join.description': '有兴趣成为Qubic大使吗？连接您的钱包以探索机会并开始为生态系统做出贡献。',
      'visitor.why.join': '为什么要加入该计划？',
      'visitor.why.join.description': '成为Qubic社区的一部分，为您的贡献获得奖励',
      'visitor.community.building': '社区建设',
      'visitor.community.building.description': '与其他大使联系，通过引人入胜的内容和活动发展Qubic社区。',
      'visitor.track.performance': '跟踪表现',
      'visitor.track.performance.description': '通过实时分析监控您的影响，了解您的贡献如何推动参与度。',
      'visitor.earn.rewards': '获得奖励',
      'visitor.earn.rewards.description': '完成任务并在排行榜上攀升，在社区中获得积分和认可。',
      'visitor.connect.wallet.step': '连接您的Qubic钱包',
      'visitor.verification.step': '完成验证过程',
      'visitor.start.earning.step': '开始为贡献赚取积分',
      'visitor.twitter.badge': '🐦 Twitter',
      'visitor.github.badge': '💻 GitHub',
      'visitor.content.badge': '📝 内容',
      'visitor.social.media.engagement': '社交媒体参与',
      'visitor.technical.contributions': '技术贡献',
      'visitor.educational.content': '教育内容创作',
      'leaderboard.this.week': '本周',
      'leaderboard.all.time': '所有时间',
      'leaderboard.last.activity': '最后活动',
      'leaderboard.top.contributor': '顶级贡献者',
      'leaderboard.active.contributor': '活跃贡献者',
      'leaderboard.rising.star': '新星',
      'leaderboard.ambassador': '大使',
      'leaderboard.just.now': '刚刚',
      'leaderboard.hours.ago': '小时前',
      'leaderboard.days.ago': '天前',
      'recent.activity.title': '最近活动',
      'recent.activity.no.activity': '未找到最近活动。',
      'recent.activity.start.contributing': '开始贡献以在此处查看您的活动！',
      'recent.activity.points': '积分',
      'recent.activity.points.plural': '积分',
      
      // Dashboard Stats
      'from.last.week': '从上周开始',
      'this.week': '本周',
      'up.positions': '上升',
      'positions': '位置',
      'points.this.week': '本周积分',
      
      // Charts
      'your.contribution.trend': '您的贡献趋势',
      'contribution.types': '贡献类型',
      'your.points': '您的积分',
      'community.average': '社区平均',
      
      // ContributionForm
      'url': 'URL',
      'url.paste.description': '粘贴您贡献的URL（Twitter帖子、GitHub提交等）',
      'description.optional': '描述（可选）',
      'brief.description': '您贡献的简要描述...',
      'validation.rules': '验证规则',
      'validation.rule.1': 'URL必须是公开和可访问的',
      'validation.rule.2': 'Twitter帖子必须提及@QubicOfficial或#Qubic',
      'validation.rule.3': 'GitHub提交必须在与Qubic相关的存储库中',
      'validation.rule.4': '重复提交将被拒绝',
      'validation.rule.5': '每种贡献类型都有冷却期',
      
      // Analytics
      'your.performance': '您的表现',
      'weekly.average': '每周平均',
      'best.week': '最佳周',
      'consistency.score': '一致性得分',
      'total.streak': '总连胜',
      'monthly.goal': '月度目标',
      'target': '目标',
      'points.to.go': '剩余积分',
      'days.remaining': '剩余天数',
      'detailed.analytics': '详细分析',
      'points.unit': '积分',
      'days.unit': '天',
    },
  };

  return translations[lang] || translations.en;
} 