version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: qubic-ambassador-backend
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - PORT=3000
      - JWT_SECRET=supersecretpassword
      - MONGO_URI=mongodb://root:password@mongo:27017/nestdb?authSource=admin
      - NODE_ENV=development
    depends_on:
      - mongo
    command: npm run start:dev

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: